apiVersion: v1
kind: Pod
metadata:
  name: contato-pod
  labels:
        app: contato-pod
spec:
  containers:
    - name: contatopod
      image: franciscoasantana/contatos
      ports:
        - containerPort: 8080