apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-pod
  labels:
    app: rabbitmq-pod
  annotations:
    author: Francisco Santana
    app-version: 1.0.0
spec:
  containers:
    - name: rabbitmqpod
      image: rabbitmq:management
      ports:
        - containerPort: 5672
        - containerPort: 15672