apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-nodeport-svc
spec:
  ports:
  - port: 5672
    name: servico
    protocol: TCP
    targetPort: 5672
  - port: 15672
    name: front
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq-pod
  type: NodePort