apiVersion: v1
kind: Pod
metadata:
  name: sqlserver-pod
  labels:
        app: sqlserver-pod
spec:
  containers:
    - name: sqlserverpod
      image: mcr.microsoft.com/mssql/server:2022-latest
      ports:
        - containerPort: 1433
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: "Developer"  # Você pode usar "Express", "Standard", ou "Enterprise" também.
        - name: SA_PASSWORD
          value: "1q2w3e4r@#$"