global:
    scrape_interval: 10s

scrape_configs: 
  - job_name: "contatos-metrics-job"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]
        
  - job_name: "regioes-metrics-job"
    metrics_path: /metrics
    static_configs:
      - targets: [ "localhost:5000" ]