apiVersion: v1
kind: Service
metadata:
  labels:
    app: contato
  name: contato-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: contato-api
  type: NodePort