apiVersion: apps/v1
kind: Deployment
metadata:
  name: contato-api
  labels:
    app: contato-api
  annotations:
    author: Francisco Santana
    app-version: 1.0.0
spec:
  replicas : 2    
  selector:
    matchLabels:
      app: contato-api
  template:
    metadata:
      labels:
        app: contato-api
    spec:
     containers:
     - name: contato-container
       image: franciscoasantana/contatos
       env:
         - name: ASPNETCORE_ENVIRONMENT
           value: Development
       ports:
       - containerPort: 8080
       livenessProbe:
         httpGet:
           path: /health
           port: 8080
         initialDelaySeconds: 5
         periodSeconds: 10
         failureThreshold: 3
         successThreshold: 1
         timeoutSeconds: 2
       envFrom:
       - configMapRef:
           name: config