apiVersion: v1
kind: Pod
metadata:
  name: contato-pod
  labels:
    app: contato-pod
  annotations:
    author: Francisco Santana
    app-version: 1.0.0
spec:
  containers:
  - name: contatopod
    image: franciscoasantana/contatos
    ports:
    - containerPort: 8080
    envFrom:
    - configMapRef:
        name: config