apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-svc
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30030
  selector:
    app: grafana-k8s
  type: NodePort