apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-k8s
  labels:
    app: grafana-k8s
  annotations:
    author: Francisco Santana
    app-version: 1.0.0
spec:
  replicas : 2    
  selector:
    matchLabels:
      app: grafana-k8s
  template:
    metadata:
      labels:
        app: grafana-k8s
    spec:
     containers:
     - name: grafana-container
       image: ramiromilena/grafana:v3
       ports:
       - containerPort: 3000
       envFrom:
       - configMapRef:
           name: config