apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus-svc
spec:
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090
  selector:
    app: prometheus-k8s
  type: NodePort