apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: contato-pvc-sql
  labels:
    name: contato-pvc-sql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: standard